all:
	g++ -c main.cpp -std=c++14
	g++ -c map.cpp -std=c++14
	g++ -c actor.cpp -std=c++14
	g++ main.o map.o actor.o -o project -std=c++14
clean:
	rm -rf project
	rm -rf main.o
	rm -rf map.o
	rm -rf actor.o